find_library(MATH_LIB m)

set(POLYBENCH_LIB_PATH "${CMAKE_CURRENT_LIST_DIR}/../lib")

function(add_polybench_library TARGET)
    cmake_parse_arguments(PARSE_ARGV 1 ARG "" "KERNEL" "OPTIONS")

    set(correlation_SOURCE datamining/correlation.c)
    set(covariance_SOURCE datamining/covariance.c)
    set(gemm_SOURCE linear-algebra/blas/gemm.c)
    set(gemver_SOURCE linear-algebra/blas/gemver.c)
    set(gesummv_SOURCE linear-algebra/blas/gesummv.c)
    set(symm_SOURCE linear-algebra/blas/symm.c)
    set(syr2k_SOURCE linear-algebra/blas/syr2k.c)
    set(syrk_SOURCE linear-algebra/blas/syrk.c)
    set(trmm_SOURCE linear-algebra/blas/trmm.c)
    set(two_mm_SOURCE linear-algebra/kernels/2mm.c)
    set(three_mm_SOURCE linear-algebra/kernels/3mm.c)
    set(atax_SOURCE linear-algebra/kernels/atax.c)
    set(bicg_SOURCE linear-algebra/kernels/bicg.c)
    set(doitgen_SOURCE linear-algebra/kernels/doitgen.c)
    set(mvt_SOURCE linear-algebra/kernels/mvt.c)
    set(cholesky_SOURCE linear-algebra/solvers/cholesky.c)
    set(durbin_SOURCE linear-algebra/solvers/durbin.c)
    set(gramschmidt_SOURCE linear-algebra/solvers/gramschmidt.c)
    set(lu_SOURCE linear-algebra/solvers/lu.c)
    set(ludcmp_SOURCE linear-algebra/solvers/ludcmp.c)
    set(trisolv_SOURCE linear-algebra/solvers/trisolv.c)
    set(deriche_SOURCE medley/deriche.c)
    set(floyd_warshall_SOURCE medley/floyd-warshall.c)
    set(nussinov_SOURCE medley/nussinov.c)
    set(adi_SOURCE stencils/adi.c)
    set(fdtd_2d_SOURCE stencils/fdtd-2d.c)
    set(heat_3d_SOURCE stencils/heat-3d.c)
    set(jacobi_1d_SOURCE stencils/jacobi-1d.c)
    set(jacobi_2d_SOURCE stencils/jacobi-2d.c)
    set(seidel_2d_SOURCE stencils/seidel-2d.c)

    add_library(${TARGET} STATIC
        "${POLYBENCH_LIB_PATH}/src/polybench.c"
        "${POLYBENCH_LIB_PATH}/src/${${ARG_KERNEL}_SOURCE}"
    )
    target_include_directories(${TARGET} PUBLIC "${POLYBENCH_LIB_PATH}/include")
    if(MATH_LIB)
        target_link_libraries(${TARGET} PUBLIC ${MATH_LIB})
    endif()

    if(MINI_DATASET IN_LIST ARG_OPTIONS)
        target_compile_definitions(${TARGET} PUBLIC MINI_DATASET)
    endif()
    if(SMALL_DATASET IN_LIST ARG_OPTIONS)
        target_compile_definitions(${TARGET} PUBLIC SMALL_DATASET)
    endif()
    if(MEDIUM_DATASET IN_LIST ARG_OPTIONS)
        target_compile_definitions(${TARGET} PUBLIC MEDIUM_DATASET)
    endif()
    if(LARGE_DATASET IN_LIST ARG_OPTIONS)
        target_compile_definitions(${TARGET} PUBLIC LARGE_DATASET)
    endif()
    if(EXTRALARGE_DATASET IN_LIST ARG_OPTIONS)
        target_compile_definitions(${TARGET} PUBLIC EXTRALARGE_DATASET)
    endif()

    if(DATA_TYPE_IS_INT IN_LIST ARG_OPTIONS)
        target_compile_definitions(${TARGET} PUBLIC DATA_TYPE_IS_INT)
    endif()
    if(DATA_TYPE_IS_FLOAT IN_LIST ARG_OPTIONS)
        target_compile_definitions(${TARGET} PUBLIC DATA_TYPE_IS_FLOAT)
    endif()
    if(DATA_TYPE_IS_DOUBLE IN_LIST ARG_OPTIONS)
        target_compile_definitions(${TARGET} PUBLIC DATA_TYPE_IS_DOUBLE)
    endif()
endfunction()
