include_guard(GLOBAL)

set(POLYBENCH_PATH "${CMAKE_CURRENT_LIST_DIR}/..")

function(add_polybench_executable TARGET)
    cmake_parse_arguments(PARSE_ARGV 1 ARG "" "KERNEL" "")

    set(correlation_SOURCE datamining/correlation_main.c)
    set(covariance_SOURCE datamining/covariance_main.c)
    set(gemm_SOURCE linear-algebra/blas/gemm_main.c)
    set(gemver_SOURCE linear-algebra/blas/gemver_main.c)
    set(gesummv_SOURCE linear-algebra/blas/gesummv_main.c)
    set(symm_SOURCE linear-algebra/blas/symm_main.c)
    set(syr2k_SOURCE linear-algebra/blas/syr2k_main.c)
    set(syrk_SOURCE linear-algebra/blas/syrk_main.c)
    set(trmm_SOURCE linear-algebra/blas/trmm_main.c)
    set(two_mm_SOURCE linear-algebra/kernels/2mm_main.c)
    set(three_mm_SOURCE linear-algebra/kernels/3mm_main.c)
    set(atax_SOURCE linear-algebra/kernels/atax_main.c)
    set(bicg_SOURCE linear-algebra/kernels/bicg_main.c)
    set(doitgen_SOURCE linear-algebra/kernels/doitgen_main.c)
    set(mvt_SOURCE linear-algebra/kernels/mvt_main.c)
    set(cholesky_SOURCE linear-algebra/solvers/cholesky_main.c)
    set(durbin_SOURCE linear-algebra/solvers/durbin_main.c)
    set(gramschmidt_SOURCE linear-algebra/solvers/gramschmidt_main.c)
    set(lu_SOURCE linear-algebra/solvers/lu_main.c)
    set(ludcmp_SOURCE linear-algebra/solvers/ludcmp_main.c)
    set(trisolv_SOURCE linear-algebra/solvers/trisolv_main.c)
    set(deriche_SOURCE medley/deriche_main.c)
    set(floyd_warshall_SOURCE medley/floyd-warshall_main.c)
    set(nussinov_SOURCE medley/nussinov_main.c)
    set(adi_SOURCE stencils/adi_main.c)
    set(fdtd_2d_SOURCE stencils/fdtd-2d_main.c)
    set(heat_3d_SOURCE stencils/heat-3d_main.c)
    set(jacobi_1d_SOURCE stencils/jacobi-1d_main.c)
    set(jacobi_2d_SOURCE stencils/jacobi-2d_main.c)
    set(seidel_2d_SOURCE stencils/seidel-2d_main.c)

    add_executable(${TARGET} "${POLYBENCH_PATH}/src/${${ARG_KERNEL}_SOURCE}")
endfunction()
