set(POLYBENCH_EXECUTABLE_PATH "${CMAKE_CURRENT_LIST_DIR}/../executable")

function(add_polybench_executable TARGET)
    cmake_parse_arguments(PARSE_ARGV 1 ARG "" "NAME;KERNEL" "")

    set(correlation_SOURCE datamining/correlation.c)
    set(covariance_SOURCE datamining/covariance.c)
    set(gemm_SOURCE linear-algebra/blas/gemm.c)
    set(gemver_SOURCE linear-algebra/blas/gemver.c)
    set(gesummv_SOURCE linear-algebra/blas/gesummv.c)
    set(symm_SOURCE linear-algebra/blas/symm.c)
    set(syr2k_SOURCE linear-algebra/blas/syr2k.c)
    set(syrk_SOURCE linear-algebra/blas/syrk.c)
    set(trmm_SOURCE linear-algebra/blas/trmm.c)
    set(2mm_SOURCE linear-algebra/kernels/2mm.c)
    set(3mm_SOURCE linear-algebra/kernels/3mm.c)
    set(atax_SOURCE linear-algebra/kernels/atax.c)
    set(bicg_SOURCE linear-algebra/kernels/bicg.c)
    set(doitgen_SOURCE linear-algebra/kernels/doitgen.c)
    set(mvt_SOURCE linear-algebra/kernels/mvt.c)
    set(cholesky_SOURCE linear-algebra/solvers/cholesky.c)
    set(durbin_SOURCE linear-algebra/solvers/durbin.c)
    set(gramschmidt_SOURCE linear-algebra/solvers/gramschmidt.c)
    set(lu_SOURCE linear-algebra/solvers/lu.c)
    set(ludcmp_SOURCE linear-algebra/solvers/ludcmp.c)
    set(trisolv_SOURCE linear-algebra/solvers/trisolv.c)
    set(deriche_SOURCE medley/deriche.c)
    set(floyd-warshall_SOURCE medley/floyd-warshall.c)
    set(nussinov_SOURCE medley/nussinov.c)
    set(adi_SOURCE stencils/adi.c)
    set(fdtd-2d_SOURCE stencils/fdtd-2d.c)
    set(heat-3d_SOURCE stencils/heat-3d.c)
    set(jacobi-1d_SOURCE stencils/jacobi-1d.c)
    set(jacobi-2d_SOURCE stencils/jacobi-2d.c)
    set(seidel-2d_SOURCE stencils/seidel-2d.c)

    add_executable(${TARGET} "${POLYBENCH_EXECUTABLE_PATH}/${${ARG_NAME}_SOURCE}")
    target_link_libraries(${TARGET} ${ARG_KERNEL})
endfunction()
